### ISSUE TITLE
Issues with 1.1.0 release artifacts

### ISSUE THREAD

**Issue by mgerstner** [01org/tpm2-abrmd#102]
While packaging abrmd for SUSE Linux I've come across the following issues:

- the release tarball https://github.com/01org/tpm2-abrmd/releases/download/1.1.0/tpm2-abrmd-1.1.0.tar.gz does not contain any _*.md_ files and not the _LICENSE_ file, also the bootstrap file is missing (well, this one can be argued).
- the AC_INIT macro in configure.ac contains a call to `git describe --tags --always- -dirty` for determining the current release tag for embedding the version into the abrmd binary. This is broken in the source tarballs, because there's no git repo to get the version from. The result is a lot of error messages during building, because git is not found / fails. Also the version number in the resulting binary will then be empty. There would be needed some additional logic such that `make dist` will generate a fixed version string or something like it.
- maybe it's possible for you to provide detached GPG signatures for the release artifacts? Or at least SHA sums for all the artifacts for simple checking of the authenticity of the downloaded archives.

Regards

Matthias

**Comment by flihp** [comment]
Thanks for taking a look at this Matthias. My eventual goal is to provide signed tarballs like you suggest but it sounds like I've got some work to do before then. Fixing the issue from your first bullet above should be as simple as adding these files to `EXTRA_DIST`. We may end up arguing a bit w/r to the bootstrap script though and my preference would be to omit this file since we distribute the `configure` script and the user should be running `./configure` and not any of the autotools (autoreconf etc).

Which brings us to your second bullet ... This macro is only interpreted when `autoconf` is run and the intent behind distributing the `configure` script is to keep users from regenerating it. This is what you're doing though?

**Comment by mgerstner** [comment]
Yes I think the _bootstrap_ script is not required for the release tarball, I just wanted to point to it for completeness and bring it into the discussion.

Since the release tarball is currently missing the documentation and _LICENSE_ file (you know, legal stuff) I've switched to the [source tarball](https://github.com/01org/tpm2-abrmd/archive/1.1.0.tar.gz) instead. And that doesn't ship the generated configure scripts so I'm forced to run the _bootstrap_ script.

Once there is a fixed release tarball I can switch back to that one and avoid calling `autoconf`. So there will be no more problem for me. Still the question remains how one can create a valid build from the source tarball when the version handling is broken without `git`. Don't know if that is a valid use case, might not be worth the trouble.

**Comment by flihp** [comment]
Understood. The root cause then is the missing files. Once those are fixed and you're using the release tarball I'll think about how to handle the source tarballs that git makes. Hopefully I can just disable these things.

**Comment by flihp** [comment]
I've created #104, #105 and #106 to track the 3 issues identified in this issue. Please engage on each issue individually.
