### ISSUE TITLE
tpmdd vs. tpm2-abrmd

### ISSUE THREAD

**Issue by danglus** [01org/tpm2-abrmd#188]
Hi,
  What are the relationships between the kernel resource manager (https://sourceforge.net/p/tpmdd/mailman/tpmdd-devel/) and this project?
  What are the guidelines for using one vs. the other?

(this is a followup to https://github.com/01org/tpm2-tss/issues/552#issuecomment-332249601)

   Thanks,
Dan

**Comment by flihp** [comment]
Good question. Jarkko and I did a talk about this very subject @ LPC 2 weeks back but the talk wasn't recorded and the LPC website doesn't have a link to the slide deck (https://www.linuxplumbersconf.org/2017/ocw/proposals/4675) so I'll summarize here a bit.

The current implementations are mostly equivalent. They both provide isolation between objects & sessions created by different connections. Given this, the reason we have both still is that we have customers running with kernels going back to the 3.x series and the kernel RM is only available on very recent kernels. So the user space RM will be around at least till everyone is using the kernel RM.

For how we get to the ideal future of a single RM in the kernel: my plan is to prototype various features in user space as a way to get them tested. There's a lot of stuff in the related TCG spec that we haven't yet implemented and we all agree that trying to put features into the kernel before we really believe them to be useful, understand how they work, and how they're going to be used by applications is a bad idea.

A good example of this are the asynchronous portions of the SAPI. Right now with the kernel RM you can use the async API but it won't really be async (calls to functions that should be async will block) since the kernel doesn't supply user space with an async / polling I/O interface. For the short term, if you want to use the SAPI in an event driven I/O framework you will only get async I/O from the user space resource manager. In the long run though, *if* this feature is important to folks we can work with the kernel folks to add support there. My plan is to treat future features in the same way.

Hope this helps clear things up a bit.

**Comment by martinezjavier** [comment]
@flihp that's very good information, do you think that could add something like that in the docs or the project wiki? (instead having it buried in an issue likely to be closed soon).

Also it would be great if you can share your LPC talk slides, maybe in the mailing list.

**Comment by flihp** [comment]
I'm trying to get the LPC organizers to expose the link through their site. If that fails I'll host them myself.

Getting data on the wiki is always a good idea. I'm planning to dump some hours into documentation once we work out the session mgmt stuff for the tools policy mechanism.

**Comment by martinezjavier** [comment]
@flihp great, thanks!

**Comment by martinezjavier** [comment]
FYI, @flihp [sildes](http://linuxplumbersconf.com/2017/ocw//system/presentations/4818/original/TPM2-kernel-evnet-app_tricca-sakkinen.pdf) are now available at LPC site.

**Comment by flihp** [comment]
Excellent! A friend sent me a link to the Linux Security Summit 2017 roundup (http://blog.namei.org/2017/10/02/linux-security-summit-2017-roundup/) that @xjamesmorris put together after the event and it has a link too. Naturally I have a typo in the file name for the slides (http://linuxplumbersconf.com/2017/ocw//system/presentations/4818/original/TPM2-kernel-evnet-app_tricca-sakkinen.pdf) so at least I'm staying true to form :stuck_out_tongue_winking_eye:

**Comment by flihp** [comment]
Where did you all find that link? I've been clicking around the LPC website for a few minutes and I can't manage to find it. There's no link from the page for the talk or the schedule ...

**Comment by martinezjavier** [comment]
@flihp in the TPM micro conf page https://www.linuxplumbersconf.org/2017/ocw/events/LPC2017/tracks/639

**Comment by flihp** [comment]
thx for the pointer @martinezjavier. I'd hoped it would be linked from the refereed track talk that we gave but this is better than nothing.

**Comment by martinezjavier** [comment]
@flihp I think this can be closed now.

**Comment by flihp** [comment]
thx @martinezjavier
