### ISSUE TITLE
tcti-tabrmd.h or tcti_tabrmd.h?

### ISSUE THREAD

**Issue by liuqun** [01org/tpm2-abrmd#68]
There seems to be 2 different name styles when we name C/C++ header files under the tcti directory.

In https://github.com/01org/TPM2.0-TSS/tree/master/include/tcti , it use an underline:
tcti_device.h
tcti_socket.h

but currently in tpm2-abrmd, a dash is in use:
tcti-tabrmd.h
https://github.com/01org/tpm2-abrmd/blob/master/src/include/tcti-tabrmd.h

**Comment by flihp** [comment]
Your attention to detail is impressive @liuqun 😄 

My plan is to move everything over to using a hyphen (instead of underscore) in file names to save everyone an additional press of the SHIFT key. I started with the new code in the tpm2-abrmd. For the master branch of the TSS we'll eventually rename these files. The 1.x branch of the TSS will keep using the underscore for backward compatibility.

Sound reasonable?

**Comment by liuqun** [comment]
@flihp Maybe we could create symbol links from tcti_device.h to tcti-device.h for backward compatibility.

**Comment by flihp** [comment]
I wasn't planning on doing any renaming till the 2.0.0 release of the TSS (later this year). Releases from the 1.x branch will remain unaffected. I figured that to be sufficient backward compatibility but adding simlinks would be a nice touch.

**Comment by flihp** [comment]
Thanks for the ideas @liuqun. Will keep this in mind when we start moving the TSS in this direction.
